export const urlBase= `${window.location.protocol}//${window.location.hostname}:${window.location.port}/app_rest/`
export const urlBaseFronted = `${window.location.protocol}//${window.location.hostname}:${window.location.port}/teo/`
export const urlJarvis= `${window.location.protocol}//${window.location.hostname}/jarvis_rest/`
export const urlJarvisBase =  urlJarvis.slice(0,-12);
export const urlMetabase='https://jarvis.grupokonecta.local/metabase/';
export const urlAnalitikas='https://matomo.grupokonecta.local/';
export const urlBookStack = 'https://jarvis.grupokonecta.local/bookstack/';
export const urlRocketchat = 'https://cdgchat.grupokonecta.local';
export const urlKosmos = 'https://kosmos.grupokonecta.com/';
export const urlChatKonectados = 'https://chatkonectados.grupokonecta.cl/home';
export const urlPowerBI = 'https://powerbi.com';
export const urlPowerBIApp = 'https://app.powerbi.com';
export const urlEnjoy = 'https://www.puntosjoys.com';
export const urlMapBox = 'https://api.mapbox.com';
export const urlXmlNamespace = 'http://www.w3.org';
export const socketHost = `${window.location.protocol}//${window.location.hostname}:`;
